(*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *)

let sum_even_fib = 
  let rec aux a b accum =
    if b >= 4000000 then accum
    else if (b mod 2) = 0 then aux b (a+b) (accum+b)
    else aux b (a+b) accum
  in aux 1 2 0
;;

let _ = print_int (sum_even_fib)
